### ISSUE TITLE
Let me connect to my server's postgresql

### ISSUE THREAD

**Issue by zuoshipinSHEKL** [akiver/cs-demo-manager#647]
### What problem is this solving

open connect servers postgresql .not just can use local

### Proposed solution

open connect servers postgresql .not just can use local

**Comment by akiver** [comment]
You can use a remote database - set the hostname to your IP server from the settings.

**Comment by zuoshipinSHEKL** [comment]
![4dbb00ec18cc1ecd96e4f8778ddcc511](https://github.com/akiver/cs-demo-manager/assets/36996379/8a1e9e03-72e8-4e7d-b7ac-267cbbc5c268)

![6eed720291075a5e8a21401f53d09bfa](https://github.com/akiver/cs-demo-manager/assets/36996379/bafed276-aad3-479b-9440-d1186bac9cec)
 
![126fc69fa717f51f21d037d9fae6ab53](https://github.com/akiver/cs-demo-manager/assets/36996379/23ec9ca5-f719-422b-b33c-e5b50407a55c)

I tried . but CSDM V3 cant connet remote database .

**Comment by zuoshipinSHEKL** [comment]
> You can use a remote database - set the hostname to your IP server from the settings.

![4dbb00ec18cc1ecd96e4f8778ddcc511](https://github.com/akiver/cs-demo-manager/assets/36996379/03775bc7-d431-418b-867d-2485771bd5c7)
![126fc69fa717f51f21d037d9fae6ab53](https://github.com/akiver/cs-demo-manager/assets/36996379/97bd24f8-e420-4701-8e16-5ec6387d5240)
I tried . but CSDM V3 cant connet remote database .

**Comment by akiver** [comment]
> PSQL binary not found

Please read the doc https://cs-demo-manager.com/docs/faq/installation

**Comment by akiver** [comment]
Why are you trying to install the shell extension on your server?
Your issue has nothing to do with it, the problem is that the **psql** binary is not in your `PATH` environment variable on your **local machine**, not your server.

The doc that you should read and understand is https://cs-demo-manager.com/docs/faq/installation#psql-binary-not-found.  
It clearly says to follow the instructions in step 2 of the installation process to fix the problem https://cs-demo-manager.com/docs/installation#step-2-setup-psql.  
**You have to install the psql CLI on your Windows machine**
