### ISSUE TITLE
when watch player highlights from faceit demos, the demo manager always plays the full Pov from the very beginning instead of actual highlights

### ISSUE THREAD

**Issue by ChengHeEric** [akiver/cs-demo-manager#728]
### Describe the bug

when watch player highlights from faceit demos, the demo manager always plays the full Pov from the very beginning instead of actual highlights

### Steps to reproduce

1. download demo from faceit
2. unpack
3. click the demo and open with CSDM
4. analyze the video
5. click on one player and click watch highlights

### Expected behavior

CSDM will play player highlights during the round - player's all kills during the round 

### How often does this bug happen?

Every time

### Environment information

Version: 3.1.0
OS: win32 x64 10.0.22631
Electron: 28.1.0
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2023-12-06T12:14:16.490Z

**Comment by akiver** [comment]
Could you upload the demo and indicate the player's name?
Also, make sure to keep the [CS2 window focused](https://cs-demo-manager.com/docs/faq/playback#the-camera-doesnt-focus-on-the-player).

I tried with a Faceit demo without issue.

https://github.com/akiver/cs-demo-manager/assets/1842524/28bde9e2-0105-4c0d-8c7c-844a2bb47cfb

**Comment by ChengHeEric** [comment]
demo link: https://www.faceit.com/zh/cs2/room/1-1a968e4a-9807-4828-b78d-a72c9a25996b
player name: cowboy


https://github.com/akiver/cs-demo-manager/assets/102639385/7690e15a-8d2e-4981-ad18-e4cf33bc2a15

**Comment by akiver** [comment]
The game starts fine for me - the camera is not on the correct player, but the playback starts a few seconds before the cowboy kills.
It's not normal that you have to click twice to start the demo.
What's the output of the CS2 console when it stops on the main menu?
Could you please send the application logs? (Settings -> About)

**Comment by ChengHeEric** [comment]
[csdm.log](https://github.com/akiver/cs-demo-manager/files/13853652/csdm.log)

[console output.txt](https://github.com/akiver/cs-demo-manager/files/13853669/console.output.txt)

both console output and log are attached, please check

**Comment by akiver** [comment]
It looks like it's a CSGO/CS2 encoding issue.

The command that starts CS2 (note the chars `何成大帅哥` in the demo path)
```
"C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\bin\win64\cs2.exe" -insecure +playdemo "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\replays\何成大帅哥\test.dem"
```

And the path seen by the game:
```
"C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\replays\ γɴ ˧  \test.dem"
```

Also from the CS2 console:

![c](https://github.com/akiver/cs-demo-manager/assets/1842524/79e89a5b-756a-4dad-ae09-9e3e56faeaca)

I tried with CSGO and it's the same thing:


![csgo](https://github.com/akiver/cs-demo-manager/assets/1842524/c4f11a22-a3c2-45bc-9faf-eb5e0ab76e66)

The playback starts the second time you click on "Watch" because the `playdemo` command is sent and executed directly from the game (not with the `+playdemo` launch parameter).  
The playback starts at the beginning of the demo because since the demo's path is incorrect - the path of the JSON file read by the CS:DM plugin is also incorrect.

I don't think we can do something about it as it's a game issue.

A current solution would be to move your demos in a path that contains only ASCII characters.

**Comment by ChengHeEric** [comment]
I will try later today and see if I can get it right

**Comment by ChengHeEric** [comment]
after i changed the demo path, i can watch the highlights and lowlights. But a new issue arised: the camera is not on the right player during the replay.

**Comment by ChengHeEric** [comment]
video link here: https://www.dropbox.com/scl/fi/i9ifz591heio8tgspb30a/2024-01-13-12-35-47.mp4?rlkey=vqasv6zbsbedg5ectncvfzc0g&dl=0

**Comment by akiver** [comment]
> the camera is not on the right player during the replay.

Yes that's another issue - you will be able to change the key sent to the game to focus on a player in the next version. (it's an edge case that can happen with some demos).

**Comment by ChengHeEric** [comment]
Great, I think we can close this issue. Thanks!

**Comment by akiver** [comment]
The next version will detect if the demo's path is CS compatible and show a message if it's not the case when trying to watch it.
