### ISSUE TITLE
Missing Data in xlsx export

### ISSUE THREAD

**Issue by Dying-Ducks** [akiver/cs-demo-manager#790]
### What problem is this solving

Using the xlsx export function reveals that the .xlsx file is "missing" a lot a data.

In the "csgo version" of the demo manager one could easily recreate the overview the manager displays after the analysis with the information within .xlsx file.
Now you can’t do that, as things like
-MVP
-Score
-All Utility related data (like everything, utility isn’t mentioned once in the .xlsx)
-In depth Weapon data like damage/shots/hits/accuracy for each weapon per player
-opening deals stats
are not in the exported .xlsx file. So the demo manager has far more information than it gives you through the xlsx export.

### Proposed solution

It would be nice if the missing data could be "added back" and we are able to export every information the demo manager pulled from the demo with the .xlsx export.

**Comment by akiver** [comment]
👋 
The next version will provide more data in XLSX exports (see related commits for details).
Because it would be impossible to fit everyone's needs, you could generate your own export using SQL.
See [this documentation](https://cs-demo-manager.com/docs/guides/export).

Adding SQL examples to the documentation is also a possibility.
