### ISSUE TITLE
Cant play CS GO demos

### ISSUE THREAD

**Issue by HrK3FTW** [akiver/cs-demo-manager#809]
### Describe the bug

I have a lot of CSGO demos back from 2023 and 2022, i was always watching them with CSGO Demos manager and i still have that program installed.
Version i have installed is 2.13.15
I have new version of CS demos manager installed too but that doesnt work either
Whenever i try to start demo it starts CS2 and just stops on menu.

### Steps to reproduce

1. Start CS GO Demos manager
2. Analyze any CSGO demo
3. Click on Watch

### Expected behavior

I am expecting csgo to start because i have csgo legacy version installed, or maybe even to ask what game to start but instead its starting CS2 always

### How often does this bug happen?

Every time

### Environment information

Version : 2.13.15
OS : Windows 10

**Comment by akiver** [comment]
The V2 will not receive any update, and the support has ended since the V3 release.

If you are encountering the issue with the V3, please create a new issue with a link to download the demo.
Also, please read [this documentation](https://cs-demo-manager.com/docs/faq/playback#cs2-demo-playback-doesnt-start-or-crashes) and make sure the game is able to play the demo without the application.
