### ISSUE TITLE
Cant play CSGO demos

### ISSUE THREAD

**Issue by HrK3FTW** [akiver/cs-demo-manager#810]
### Describe the bug

I have a lot of CSGO demos back from 2023 and 2022, i was always watching them with CSGO Demos manager but now it doesnt work.
Version i have installed is 3.4.0
Whenever i try to start demo it starts CS2 instead of csgo and just stops on menu.

### Demo links

https://www.mediafire.com/file/v77fj6dkdvij47p/1-c8e35ddc-2b84-47e3-b748-62d092abd021-1-1.dem/file

### Steps to reproduce

1. Start CS Demo Manager
2. Analyze CSGO demo that u want to watch
3. Click on Watch

### Expected behavior

Im expecting that program is going to open csgo and play demo there but instead it starts cs2 which cant play csgo demos and it just stops on menu

### How often does this bug happen?

Every time

### Environment information

Version : 3.4.0
OS : Windows 10

### Additional context

All demos works cuz i can start them via console in csgo.

**Comment by akiver** [comment]
I can't reproduce the issue.
Have you selected the `csgo_legacy` branch?
Could you upload your logs file please?

![d](https://github.com/akiver/cs-demo-manager/assets/1842524/7df3146e-cf79-47c7-94ca-a6d1570d178c)

**Comment by HrK3FTW** [comment]
It doesnt even ask me what game to start, it just starts cs2.
I tried to set up steam to start csgo without asking

**Comment by akiver** [comment]
The app doesn't ask if it's a CSGO or a CS2 demo because it can detect it based on the file's header.

The app starts CS2 only if the game is `CS2` in the app which is not the case for me with your demo (it's `CSGO`).
![t](https://github.com/akiver/cs-demo-manager/assets/1842524/cdd66a26-c8a6-40a1-9c92-7c583e8b192c)
What game is displayed for you?
