### ISSUE TITLE
Errors when analyzing demos

### ISSUE THREAD

**Issue by EmSixTeen** [akiver/cs-demo-manager#815]
### Describe the bug

Trying to analyse my most recent demos leads to an error.

### Demo links

Example demo: https://drive.google.com/file/d/1GowESA3kbDRx6WNIKLKaZ2KtdyqVqgPI/view?usp=sharing

### Steps to reproduce

Go to demos tab. 
Select demo(s).
Click Analyze.

### Expected behavior

Analyzes the demos.

### How often does this bug happen?

Every time

### Log file

unknown grenade model 8528019637059176743panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x592a0e]

goroutine 1 [running]:
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.recoverFromUnexpectedEOF({0x672760, 0xc0c400})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:171 +0xd7
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd.func1()
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:124 +0xa5
panic({0x672760?, 0xc0c400?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc00028d500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:359 +0x22e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc00028d500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc00003e0ab, 0x91}, {0xa0?, {0xc00000a148?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:226 +0xb35
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc00003e0ab?, 0x91?}, {0xc000030288, 0x31}, {0x1, {0xc00000a148, 0x5}, {0xc00000a118, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:270 +0x6c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc000042090, 0x5, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45

### Environment information

Version: 3.4.0
OS: win32 x64 10.0.19045
Electron: 29.1.6
Chrome: 122.0.6261.139
Last database migrations:
v2 - 2024-04-03T18:42:14.956Z

**Comment by EmSixTeen** [comment]
Another example log:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xfc2a0e]

goroutine 1 [running]:
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.recoverFromUnexpectedEOF({0x10a2760, 0x163c400})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:171 +0xd7
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd.func1()
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:124 +0xa5
panic({0x10a2760?, 0x163c400?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc0002d1500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:359 +0x22e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc0002d1500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc00014200b, 0x91}, {0xa0?, {0xc00011a0f8?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:226 +0xb35
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc00014200b?, 0x91?}, {0xc00013c0c8, 0x31}, {0x1, {0xc00011a0f8, 0x5}, {0xc00011a0c8, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:270 +0x6c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc000144010, 0x5, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45
```

**Comment by rizz-rizz77** [comment]
I am also experiencing this issue. As soon as a demo starts analyzing it hits the same error. Every demo since 4/29/24 is affected. Here is a log:

unknown grenade model 8528019637059176743panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xd2044e]

goroutine 1 [running]:
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.recoverFromUnexpectedEOF({0xdfb840, 0x13893f0})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:171 +0xd7
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd.func1()
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:124 +0xa5
panic({0xdfb840?, 0x13893f0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc000275500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:359 +0x22e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc000275500)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc00006e0cb, 0x4f}, {0xa0?, {0xc00000a138?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:208 +0xb49
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc00006e0cb?, 0x4f?}, {0xc00002c248, 0x31}, {0x0, {0xc00000a138, 0x5}, {0xc00000a108, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:252 +0x6c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc000112010, 0x4, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45

Some of the errors do not have that first "unknown grenade model..." line.

Here is my environment information:

Version: 3.2.2
OS: win32 x64 10.0.19045
Electron: 28.2.2
Chrome: 120.0.6099.276
Last database migrations:
v1 - 2023-12-26T09:23:06.353Z
