### ISSUE TITLE
Support for SteamChina clients

### ISSUE THREAD

**Issue by EventHorizonV** [akiver/cs-demo-manager#887]
### What problem is this solving

When I start cs demo manager with SteamChina (exclusive version client produced for review in Chinese Mainland for games such as Counter Strike), it is considered that Steam has not been started. It seems that the SteamChina client is no different from the original Steam client, but the name is changed to SteamChina and it will connect to the perfectworld server in Chinese Mainland by default. Hope to add support for SteamChina.

### Proposed solution

I hope that CS Demo Manager can also be used properly when using the SteamChina client.

### Describe alternatives you've considered

Using the original Steam client may cause some connectivity issues, resulting in the inability to open demos properly.

**Comment by akiver** [comment]
The next version *should* support it.
I'm using *should* because I couldn't fully test it.
I installed the client in a VM and stopped going further after seeing this window asking for personal information.

![steam](https://github.com/akiver/cs-demo-manager/assets/1842524/e8ec48ae-a5e0-4e09-acd3-00a48dc74eb2)

The only difference seems to be the executable name - let me know if it works when the next version is released.

**Comment by EventHorizonV** [comment]
Thank you very much for your reply. I will test it after the next version is released.

**Comment by EventHorizonV** [comment]
I have tested it and it runs very well! :)
